language: node_js
node_js:
 - "node"
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST

V81SmbsPRp8sZ5e5+fafv+yMzaARoklPXU7x2Sgg4efStB9ca2G5i0qqTEdaeDFk+BJp8QaGbLv5SuTt6mBR/yhg0P/+fAD/2vsIQBQD5KJZ49hlMo8CP6DZZpOwxx+VSWRt4lJTLBxC8ODJEJ7P+LqXaOxQLSBrb7bW3ksJWtZLLpHbvyQB3zMg9El+i3rRMOi3hlrece9NZXtirYHlUwFIk6N3OcUtPr4VUVPHVMIVsgu2oNdUb+X4gkqS8YAQe1OEJaI/pFiMCWbmPxK6hpFNlKuQQz/NHmXPwLWI8kLFa+v34SI57dteivjRJP8V/X0fstEGwLXvGohofFHazxRagzyrBUz2IY55gAxIv8UqTQfcxUMwUDkznPAkVG00mZXbFfnmMHR5VEiHRw2Jf0sLjeLQLpbCJRCtIBuI/h6o/EmY1M84CuXgibR170zJ0SjaIjmyO7K98wJsP084N6kVY1PsNPJl9Ti28kgmeR01C56/qXVZ/q9oMTQLGmyCqJ85Mooa1QyH9uCrKOP0i3WvSOPnv4YtLRjEurFgNXjIIz57Lb81bCpat75BcQkgkzKMcovwTt2x8JKUN0qtcIJte2N3Mz5H3DAjDWyya5TrB/fr43u6jnAyg2KmbOKbF6HvfqWnjvppEzCjGDKNvmdzRoO0IRuXXP2+rtUaCTE=
